# Generated by Django 4.1.4 on 2022-12-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('project_image', models.ImageField(upload_to='gmiuser/')),
                ('image_1', models.ImageField(default='', upload_to='gmiuser/')),
                ('image_2', models.ImageField(default='', upload_to='gmiuser/')),
                ('image_3', models.ImageField(default='', upload_to='gmiuser/')),
                ('image_4', models.ImageField(default='', upload_to='gmiuser/')),
                ('catagory', models.CharField(max_length=150)),
            ],
        ),
    ]
