# Generated by Django 4.1.4 on 2022-12-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmeuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customername', models.CharField(max_length=150)),
                ('Emailid', models.CharField(max_length=150)),
                ('Rating', models.BigIntegerField()),
                ('Mobile', models.BigIntegerField()),
                ('Place', models.CharField(max_length=150)),
                ('Review', models.CharField(max_length=500)),
            ],
        ),
    ]
