# Generated by Django 4.1.4 on 2023-01-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmeuser', '0002_reviewdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
